spring:
  application:
    name: assetflow-market-data-aggregator
  server:
    port: 8081
  data:
    mongodb:
      uri: mongodb://sothrose:sothrose@localhost:27017/assetflow
      database: assetflow
  redis:
    host: localhost
    port: 6379
    password:

mongock:
  enabled: true
