spring:
  application:
    name: assetflow-market-data-aggregator
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: "env,configprops"
